
obj-y := test_file.o
obj-y += test_timer.o
obj-y += test_thread.o
obj-y += printime_thread.o
obj-y += ten_thread.o
obj-y += client.o
obj-y += server.o
obj-y += client1.o
obj-y += client2.o
obj-y += client3.o
obj-y += client4.o
obj-y += client5.o
obj-y += pthread_server.o
obj-y += read_pipe.o
obj-y += write_pipe.o

